In [124]:
import requests
import pandas as pd
import numpy as np
from IPython.display import display
import json
import io

## Obtain violation data from Envirofacts RESTful API

In [125]:
# Identify a url for the request
url = 'https://iaspub.epa.gov/enviro/efservice/SDW_VIOL_ENFORCEMENT/STATE/NJ/COMPPERBEGINDATE/>/31-DEC-11/COMPPERENDDATE/</01-JAN-17/CSV'
r = requests.get(url)
if r.status_code == 200:
    vio_df = pd.read_csv(io.StringIO(r.text))
else:
    raise Exception("Request was not valid. Code: {code}".format(code=r.status_code))

In [126]:
# Explore the data
with pd.option_context('display.max_columns', None):
    display(vio_df.head(5))

,SDW_VIOL_ENFORCEMENT.PWSID,SDW_VIOL_ENFORCEMENT.PWSNAME,SDW_VIOL_ENFORCEMENT.STATE,SDW_VIOL_ENFORCEMENT.COUNTYSERVED,SDW_VIOL_ENFORCEMENT.VIOID,SDW_VIOL_ENFORCEMENT.CCODE,SDW_VIOL_ENFORCEMENT.CNAME,SDW_VIOL_ENFORCEMENT.CTYPE,SDW_VIOL_ENFORCEMENT.VCODE,SDW_VIOL_ENFORCEMENT.VNAME,SDW_VIOL_ENFORCEMENT.VTYPE,SDW_VIOL_ENFORCEMENT.VIOLMEASURE,SDW_VIOL_ENFORCEMENT.ENFACTIONTYPE,SDW_VIOL_ENFORCEMENT.ENFACTIONNAME,SDW_VIOL_ENFORCEMENT.ENFDATE,SDW_VIOL_ENFORCEMENT.COMPPERBEGINDATE,SDW_VIOL_ENFORCEMENT.COMPPERENDDATE,SDW_VIOL_ENFORCEMENT.SOURCES,SDW_VIOL_ENFORCEMENT.DEFINITION,SDW_VIOL_ENFORCEMENT.HEALTH_EFFECTS,Unnamed: 20
0,NJ0609300,MAUR RIV TWP BD OF ED PO,NJ,CUMBERLAND,1922,2983,"1,2-Dichloropropane",VOC,3,"Monitoring, Regular",MR,Monitoring and Reporting,SFJ,St Formal NOV issued,12-JUL-16,01-APR-16,30-JUN-16,Discharge from industrial chemical factories,"1,2-Dichloropropane is a colorless flammable l...",Increased risk of cancer,NaN
1,NJ1429302,"JNBC ASSOCIATES, LLC",NJ,MORRIS,8025,2983,"1,2-Dichloropropane",VOC,3,"Monitoring, Regular",MR,Monitoring and Reporting,SFJ,St Formal NOV issued,17-JAN-13,01-OCT-12,31-DEC-12,Discharge from industrial chemical factories,"1,2-Dichloropropane is a colorless flammable l...",Increased risk of cancer,NaN
2,NJ1429302,"JNBC ASSOCIATES, LLC",NJ,MORRIS,8013,2378,"1,2,4-Trichlorobenzene",VOC,3,"Monitoring, Regular",MR,Monitoring and Reporting,SFJ,St Formal NOV issued,17-JAN-13,01-OCT-12,31-DEC-12,Discharge from textile finishing factories,"1,2,4-Trichlorobenzene is an aromatic, colorle...",Changes in adrenal glands,NaN
3,NJ0408001,CITY OF CAMDEN,NJ,CAMDEN,50250,2983,"1,2-Dichloropropane",VOC,3,"Monitoring, Regular",MR,Monitoring and Reporting,SFJ,St Formal NOV issued,19-OCT-16,01-JUL-16,30-SEP-16,Discharge from industrial chemical factories,"1,2-Dichloropropane is a colorless flammable l...",Increased risk of cancer,NaN
4,NJ0612001,BAYSHORE MOBILE HOME PARK,NJ,CUMBERLAND,22943,2983,"1,2-Dichloropropane",VOC,3,"Monitoring, Regular",MR,Monitoring and Reporting,SFM,St Admin Penalty assessed,19-JUN-18,01-JAN-15,31-DEC-15,Discharge from industrial chemical factories,"1,2-Dichloropropane is a colorless flammable l...",Increased risk of cancer,NaN

In [127]:
# Function to clean up headers (will be used below)
def clean_headers(df, to_remove):
    for col in df.columns:
        df = df.rename(index=str, 
                           columns={col: col.replace(to_remove,'')})
    return df

vio_df = clean_headers(vio_df, 'SDW_VIOL_ENFORCEMENT.')
vio_df.head(5)

,PWSID,PWSNAME,STATE,COUNTYSERVED,VIOID,CCODE,CNAME,CTYPE,VCODE,VNAME,...,VIOLMEASURE,ENFACTIONTYPE,ENFACTIONNAME,ENFDATE,COMPPERBEGINDATE,COMPPERENDDATE,SOURCES,DEFINITION,HEALTH_EFFECTS,Unnamed: 20
0,NJ0609300,MAUR RIV TWP BD OF ED PO,NJ,CUMBERLAND,1922,2983,"1,2-Dichloropropane",VOC,3,"Monitoring, Regular",...,Monitoring and Reporting,SFJ,St Formal NOV issued,12-JUL-16,01-APR-16,30-JUN-16,Discharge from industrial chemical factories,"1,2-Dichloropropane is a colorless flammable l...",Increased risk of cancer,NaN
1,NJ1429302,"JNBC ASSOCIATES, LLC",NJ,MORRIS,8025,2983,"1,2-Dichloropropane",VOC,3,"Monitoring, Regular",...,Monitoring and Reporting,SFJ,St Formal NOV issued,17-JAN-13,01-OCT-12,31-DEC-12,Discharge from industrial chemical factories,"1,2-Dichloropropane is a colorless flammable l...",Increased risk of cancer,NaN
2,NJ1429302,"JNBC ASSOCIATES, LLC",NJ,MORRIS,8013,2378,"1,2,4-Trichlorobenzene",VOC,3,"Monitoring, Regular",...,Monitoring and Reporting,SFJ,St Formal NOV issued,17-JAN-13,01-OCT-12,31-DEC-12,Discharge from textile finishing factories,"1,2,4-Trichlorobenzene is an aromatic, colorle...",Changes in adrenal glands,NaN
3,NJ0408001,CITY OF CAMDEN,NJ,CAMDEN,50250,2983,"1,2-Dichloropropane",VOC,3,"Monitoring, Regular",...,Monitoring and Reporting,SFJ,St Formal NOV issued,19-OCT-16,01-JUL-16,30-SEP-16,Discharge from industrial chemical factories,"1,2-Dichloropropane is a colorless flammable l...",Increased risk of cancer,NaN
4,NJ0612001,BAYSHORE MOBILE HOME PARK,NJ,CUMBERLAND,22943,2983,"1,2-Dichloropropane",VOC,3,"Monitoring, Regular",...,Monitoring and Reporting,SFM,St Admin Penalty assessed,19-JUN-18,01-JAN-15,31-DEC-15,Discharge from industrial chemical factories,"1,2-Dichloropropane is a colorless flammable l...",Increased risk of cancer,NaN

In [128]:
vio_df['health_based'] = np.where(
                        (np.logical_or(vio_df['VTYPE']=='MR',vio_df['VTYPE']=='OTHER')),'N','Y')

In [129]:
# Identify all violations for each water system
pivot = pd.pivot_table(vio_df,index=['PWSID','VIOID','health_based'])
pivot = pivot.reset_index().drop(columns=['CCODE','VCODE'])
pivot.head(10)

       PWSID        VIOID health_based
0  CT0320044       143511            N
1  CT0347031       342114            N
2  FL3424829  20120005135            N
3  FL6295268  20160000554            N
4  FL6295268  20160000555            N
5  FL6295268  20160000574            N
6  FL6295268  20160000575            N
7  FL6295268  20160000608            N
8  FL6295268  20160000609            N
9  FL6295268  20160000633            N

In [130]:
# Identify all health-based violations for each water system
health_vio_df = vio_df[vio_df.health_based=='Y']
health_pivot = pd.pivot_table(health_vio_df,index=['PWSID','VIOID','health_based'])
health_pivot = health_pivot.reset_index().drop(columns=['CCODE','VCODE'])
health_pivot.head(10)

       PWSID  VIOID health_based
0  NJ0102301   2111            Y
1  NJ0104322    811            Y
2  NJ0105301    511            Y
3  NJ0105304  11111            Y
4  NJ0105304  11112            Y
5  NJ0105323   2109            Y
6  NJ0105333   2214            Y
7  NJ0105333   2215            Y
8  NJ0105333   2216            Y
9  NJ0105333   2217            Y

In [131]:
# Summarize total violations per water system
vio_by_pws = pd.pivot_table(pivot,index=['PWSID'],aggfunc='count')
vio_by_pws = vio_by_pws.reset_index().drop(columns='health_based')
vio_by_pws = vio_by_pws.rename(columns={'VIOID': 'all_violations'})
vio_by_pws.head(5)

       PWSID  all_violations
0  CT0320044               1
1  CT0347031               1
2  FL3424829               1
3  FL6295268              12
4  GA2310025               1

In [132]:
# Summarize health-based violations per water system
health_vio_by_pws = pd.pivot_table(health_pivot,index=['PWSID'],aggfunc='count')
health_vio_by_pws = health_vio_by_pws.reset_index().drop(columns='health_based')
health_vio_by_pws = health_vio_by_pws.rename(columns={'VIOID': 'health_violations'})
health_vio_by_pws.head(5)

       PWSID  health_violations
0  NJ0102301                  1
1  NJ0104322                  1
2  NJ0105301                  1
3  NJ0105304                  2
4  NJ0105323                  1

In [133]:
# Merge tables into one datasets
sdwa_vios = pd.merge(vio_by_pws, health_vio_by_pws, how='outer', on='PWSID')

In [134]:
# Convert null values to 0
sdwa_vios.fillna(0, inplace=True)

In [135]:
sdwa_vios.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 1423 entries, 0 to 1422
Data columns (total 3 columns):
PWSID                1423 non-null object
all_violations       1423 non-null int64
health_violations    1423 non-null float64
dtypes: float64(1), int64(1), object(1)
memory usage: 44.5+ KB

In [136]:
# Convert health_violations field type to int64 to match all_violations field type
sdwa_vios['health_violations'] = sdwa_vios['health_violations'].astype('int64')

In [137]:
# Confirm dataset looks good
sdwa_vios.head(10)

       PWSID  all_violations  health_violations
0  CT0320044               1                  0
1  CT0347031               1                  0
2  FL3424829               1                  0
3  FL6295268              12                  0
4  GA2310025               1                  0
5  LA1019085               1                  0
6  ME0000802               2                  0
7  ME0094466               2                  0
8  NJ0102001               6                  0
9  NJ0102301               2                  1

In [138]:
sdwa_vios.to_csv('../data/Created/SDWIS/sdwa_vios.csv', index=False)

## Obtain water system characteristic data from Envirofacts RESTful API

In [139]:
# Identify the the table of interest
url = 'https://iaspub.epa.gov/enviro/efservice/WATER_SYSTEM/STATE_CODE/NJ/CSV'
r = requests.get(url)
if r.status_code == 200:
    pws_df = pd.read_csv(io.StringIO(r.text))
else:
    raise Exception("Request was not valid. Code: {code}".format(code=r.status_code))

In [141]:
# Filter and explore the data
pws_df = clean_headers(pws_df, 'WATER_SYSTEM.')
filters = (pws_df.STATE_CODE == 'NJ') & \
            (pws_df.PWS_ACTIVITY_CODE == 'A') & \
            (pws_df.PWS_TYPE_CODE == 'CWS')
pws_df = pws_df[filters]
pws_df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 502 entries, 0 to 9934
Data columns (total 48 columns):
PWSID                             502 non-null object
PWS_NAME                          502 non-null object
NPM_CANDIDATE                     502 non-null object
PRIMACY_AGENCY_CODE               502 non-null object
EPA_REGION                        502 non-null int64
SEASON_BEGIN_DATE                 0 non-null object
SEASON_END_DATE                   0 non-null object
PWS_ACTIVITY_CODE                 502 non-null object
PWS_DEACTIVATION_DATE             0 non-null object
PWS_TYPE_CODE                     502 non-null object
DBPR_SCHEDULE_CAT_CODE            419 non-null float64
CDS_ID                            416 non-null float64
GW_SW_CODE                        502 non-null object
LT2_SCHEDULE_CAT_CODE             30 non-null float64
OWNER_TYPE_CODE                   502 non-null object
POPULATION_SERVED_COUNT           502 non-null int64
POP_CAT_2_CODE                    502 non-null int64
POP_CAT_3_CODE                    502 non-null int64
POP_CAT_4_CODE                    502 non-null int64
POP_CAT_5_CODE                    502 non-null int64
POP_CAT_11_CODE                   502 non-null int64
PRIMACY_TYPE                      502 non-null object
PRIMARY_SOURCE_CODE               502 non-null object
IS_GRANT_ELIGIBLE_IND             502 non-null object
IS_WHOLESALER_IND                 502 non-null object
IS_SCHOOL_OR_DAYCARE_IND          502 non-null object
SERVICE_CONNECTIONS_COUNT         502 non-null int64
SUBMISSION_STATUS_CODE            502 non-null object
ORG_NAME                          502 non-null object
ADMIN_NAME                        502 non-null object
EMAIL_ADDR                        15 non-null object
PHONE_NUMBER                      472 non-null object
PHONE_EXT_NUMBER                  72 non-null float64
FAX_NUMBER                        159 non-null object
ALT_PHONE_NUMBER                  0 non-null float64
ADDRESS_LINE1                     501 non-null object
ADDRESS_LINE2                     74 non-null object
CITY_NAME                         502 non-null object
ZIP_CODE                          502 non-null object
COUNTRY_CODE                      502 non-null object
STATE_CODE                        502 non-null object
SOURCE_WATER_PROTECTION_CODE      485 non-null object
SOURCE_PROTECTION_BEGIN_DATE      9 non-null object
OUTSTANDING_PERFORMER             1 non-null object
OUTSTANDING_PERFORM_BEGIN_DATE    0 non-null float64
CITIES_SERVED                     502 non-null object
COUNTIES_SERVED                   502 non-null object
Unnamed: 47                       0 non-null float64
dtypes: float64(7), int64(8), object(33)
memory usage: 192.2+ KB

In [142]:
# Only utilize necessary columns
pws_clean = pws_df.filter(['PWSID',
                           'PRIMARY_SOURCE_CODE',
                           'OWNER_TYPE_CODE', 
                           'SERVICE_CONNECTIONS_COUNT',
                           'COUNTIES_SERVED'], axis=1)

In [143]:
# Merge with the rest of the PWS data
sdwa_vios_merged = pd.merge(pws_clean, sdwa_vios, how='left', on='PWSID')
sdwa_vios_merged.head()

,PWSID,PRIMARY_SOURCE_CODE,OWNER_TYPE_CODE,SERVICE_CONNECTIONS_COUNT,COUNTIES_SERVED,all_violations,health_violations
0,NJ1432001,GW,L,10,Morris,30.0,0.0
1,NJ1435002,GW,L,4350,Morris,5.0,0.0
2,NJ1503001,GW,L,2253,Ocean,1.0,1.0
3,NJ1522001,GW,L,933,Ocean,1.0,0.0
4,NJ1005001,GW,L,4600,Hunterdon,4.0,0.0

In [145]:
# Explore the dataset
pws_clean.info()

<class 'pandas.core.frame.DataFrame'>
Index: 502 entries, 0 to 9934
Data columns (total 5 columns):
PWSID                        502 non-null object
PRIMARY_SOURCE_CODE          502 non-null object
OWNER_TYPE_CODE              502 non-null object
SERVICE_CONNECTIONS_COUNT    502 non-null int64
COUNTIES_SERVED              502 non-null object
dtypes: int64(1), object(4)
memory usage: 23.5+ KB

In [147]:
sdwa_vios_merged.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 502 entries, 0 to 501
Data columns (total 7 columns):
PWSID                        502 non-null object
PRIMARY_SOURCE_CODE          502 non-null object
OWNER_TYPE_CODE              502 non-null object
SERVICE_CONNECTIONS_COUNT    502 non-null int64
COUNTIES_SERVED              502 non-null object
all_violations               305 non-null float64
health_violations            305 non-null float64
dtypes: float64(2), int64(1), object(4)
memory usage: 31.4+ KB

In [148]:
# Replace all null values in the violation fields with with 0 since if there 
# isn't violation data  for a water system that means the water system did not 
# recieve a violation.
sdwa_vios_merged.fillna(0, inplace=True)

In [150]:
# Convert violation fields to integer type
sdwa_vios_merged['health_violations'] = sdwa_vios_merged['health_violations'].astype('int64')
sdwa_vios_merged['all_violations'] = sdwa_vios_merged['all_violations'].astype('int64')

In [146]:
# Identify the full list of codes in order to convert to full names
print(set(sdwa_vios_merged['PRIMARY_SOURCE_CODE']))
print(set(sdwa_vios_merged['OWNER_TYPE_CODE']))

{'SW', 'GW', 'GU', 'GWP', 'SWP'}
{'L', 'S', 'P', 'F', 'M'}

In [151]:
# Create dictionaries with the codes
psc = {'GW': 'Ground water', 
       'SW': 'Surface water', 
       'SWP': 'Surface water purchased', 
       'GWP': 'Groundwater purchased',
       'GU': 'Ground water under influence of surface water source'}
otc = {'M': 'Mixed', 
       'S': 'State Government', 
       'F': 'Federal Government', 
       'P': 'Private', 
       'L': 'Local Government'}

def psc_to_description(code):
    return psc[code]

def otc_to_description(code):
    return otc[code]

In [152]:
sdwa_vios_merged['primary_source'] = sdwa_vios_merged['PRIMARY_SOURCE_CODE'].apply(psc_to_description)
sdwa_vios_merged['owner_type'] = sdwa_vios_merged['OWNER_TYPE_CODE'].apply(otc_to_description)

In [153]:
sdwa_vios_merged.head()

,PWSID,PRIMARY_SOURCE_CODE,OWNER_TYPE_CODE,SERVICE_CONNECTIONS_COUNT,COUNTIES_SERVED,all_violations,health_violations,primary_source,owner_type
0,NJ1432001,GW,L,10,Morris,30,0,Ground water,Local Government
1,NJ1435002,GW,L,4350,Morris,5,0,Ground water,Local Government
2,NJ1503001,GW,L,2253,Ocean,1,1,Ground water,Local Government
3,NJ1522001,GW,L,933,Ocean,1,0,Ground water,Local Government
4,NJ1005001,GW,L,4600,Hunterdon,4,0,Ground water,Local Government

In [156]:
sdwa_vios_merged.to_csv('../data/Created/SDWIS/sdwa_vios_complete.csv', index=False)